# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "monitoring" do |vm1|
    vm1.vm.hostname = "monitoring"
    vm1.vm.box = "bento/ubuntu-20.04"
    vm1.vm.network "private_network", ip: "192.178.33.50"
    vm1.vm.provision "setup-hosts", :type => "shell", :path => "./scripts/prometheus-setup.sh"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "monitoring"
      vb.gui = false
      vb.memory = "1024"
    end
  end
end